import json

def main():
    # config file will always be defined as config.json
    # must be generated by user before execution
    config_file_path = 'config.json'
    
    # Attempt to read json data into dict
    try:
        opened_json_file = open(config_file_path, 'r')
        discord_bot_config = json.load(opened_json_file)
        opened_json_file.close()
    except Exception as e:
        print(f'Unable to open config file due to the following error: \n{e}')
        quit()
    
    print(discord_bot_config)


if __name__ == "__main__":
    main()