import json
from apartment_web_scraper import ApartmentWebScraper
from apartment_data import ApartmentData

def main():
    # config file will always be defined as config.json
    # must be generated by user before execution
    config_file_path = 'config.json'
    
    # Attempt to read json data into dict
    try:
        opened_json_file = open(config_file_path, 'r')
        discord_bot_config = dict(json.load(opened_json_file))
        opened_json_file.close()
    except Exception as e:
        print(f'Unable to open config file due to the following error: \n{e}')
        quit()
    
    
    apartment_web_scraper = ApartmentWebScraper(**discord_bot_config)

    apartment_web_scraper.start_driver()

    available_apartments = apartment_web_scraper.get_available_apartments_from_url('https://www.apartments.com/crest-at-park-central-dallas-tx/pedmzer/')

    for apartment in available_apartments:
        apartment.print_all_data()

    apartment_web_scraper.quit_driver()
    

if __name__ == "__main__":
    main()